# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Jun 19 16:44:24 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(1181, 878)
        Form.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.tabMain = QtGui.QTabWidget(Form)
        self.tabMain.setObjectName(_fromUtf8("tabMain"))
        self.tabLattice = QtGui.QWidget()
        self.tabLattice.setObjectName(_fromUtf8("tabLattice"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tabLattice)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabLattice)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl0_12 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_12.setObjectName(_fromUtf8("lbl0_12"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_12)
        self.Run_name____name = QtGui.QLineEdit(self.groupBox_4)
        self.Run_name____name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Run_name____name.setInputMask(_fromUtf8(""))
        self.Run_name____name.setMaxLength(256)
        self.Run_name____name.setObjectName(_fromUtf8("Run_name____name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Run_name____name)
        self.lbl0_2 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_2.setObjectName(_fromUtf8("lbl0_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_2)
        self.Lattice_parameters____c0 = QtGui.QComboBox(self.groupBox_4)
        self.Lattice_parameters____c0.setObjectName(_fromUtf8("Lattice_parameters____c0"))
        self.Lattice_parameters____c0.addItem(_fromUtf8(""))
        self.Lattice_parameters____c0.addItem(_fromUtf8(""))
        self.Lattice_parameters____c0.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.Lattice_parameters____c0)
        self.lbl0_4 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_4.setObjectName(_fromUtf8("lbl0_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_4)
        self.Lattice_parameters____beta = QtGui.QLineEdit(self.groupBox_4)
        self.Lattice_parameters____beta.setAutoFillBackground(False)
        self.Lattice_parameters____beta.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Lattice_parameters____beta.setInputMask(_fromUtf8(""))
        self.Lattice_parameters____beta.setMaxLength(128)
        self.Lattice_parameters____beta.setObjectName(_fromUtf8("Lattice_parameters____beta"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Lattice_parameters____beta)
        self.lbl0_17 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_17.setObjectName(_fromUtf8("lbl0_17"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_17)
        self.HMC_parameters____tau = QtGui.QLineEdit(self.groupBox_4)
        self.HMC_parameters____tau.setInputMethodHints(QtCore.Qt.ImhNone)
        self.HMC_parameters____tau.setInputMask(_fromUtf8(""))
        self.HMC_parameters____tau.setMaxLength(128)
        self.HMC_parameters____tau.setObjectName(_fromUtf8("HMC_parameters____tau"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.HMC_parameters____tau)
        self.lbl0_19 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_19.setObjectName(_fromUtf8("lbl0_19"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl0_19)
        self.MD_trajectories____nth = QtGui.QLineEdit(self.groupBox_4)
        self.MD_trajectories____nth.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MD_trajectories____nth.setInputMask(_fromUtf8(""))
        self.MD_trajectories____nth.setMaxLength(128)
        self.MD_trajectories____nth.setObjectName(_fromUtf8("MD_trajectories____nth"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.MD_trajectories____nth)
        self.lbl0_20 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_20.setObjectName(_fromUtf8("lbl0_20"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl0_20)
        self.MD_trajectories____ntr = QtGui.QLineEdit(self.groupBox_4)
        self.MD_trajectories____ntr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MD_trajectories____ntr.setInputMask(_fromUtf8(""))
        self.MD_trajectories____ntr.setMaxLength(128)
        self.MD_trajectories____ntr.setObjectName(_fromUtf8("MD_trajectories____ntr"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.MD_trajectories____ntr)
        self.lbl0_25 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_25.setObjectName(_fromUtf8("lbl0_25"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl0_25)
        self.MD_trajectories____dtr_log = QtGui.QLineEdit(self.groupBox_4)
        self.MD_trajectories____dtr_log.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MD_trajectories____dtr_log.setInputMask(_fromUtf8(""))
        self.MD_trajectories____dtr_log.setMaxLength(128)
        self.MD_trajectories____dtr_log.setObjectName(_fromUtf8("MD_trajectories____dtr_log"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.MD_trajectories____dtr_log)
        self.lbl0_26 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_26.setObjectName(_fromUtf8("lbl0_26"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl0_26)
        self.MD_trajectories____dtr_ms = QtGui.QLineEdit(self.groupBox_4)
        self.MD_trajectories____dtr_ms.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MD_trajectories____dtr_ms.setInputMask(_fromUtf8(""))
        self.MD_trajectories____dtr_ms.setMaxLength(128)
        self.MD_trajectories____dtr_ms.setObjectName(_fromUtf8("MD_trajectories____dtr_ms"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.MD_trajectories____dtr_ms)
        self.lbl0_27 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_27.setObjectName(_fromUtf8("lbl0_27"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.lbl0_27)
        self.MD_trajectories____dtr_cnfg = QtGui.QLineEdit(self.groupBox_4)
        self.MD_trajectories____dtr_cnfg.setInputMethodHints(QtCore.Qt.ImhNone)
        self.MD_trajectories____dtr_cnfg.setInputMask(_fromUtf8(""))
        self.MD_trajectories____dtr_cnfg.setMaxLength(128)
        self.MD_trajectories____dtr_cnfg.setObjectName(_fromUtf8("MD_trajectories____dtr_cnfg"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.MD_trajectories____dtr_cnfg)
        self.lbl0_34 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_34.setObjectName(_fromUtf8("lbl0_34"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.lbl0_34)
        self.Lattice_parameters____kappa = QtGui.QLineEdit(self.groupBox_4)
        self.Lattice_parameters____kappa.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Lattice_parameters____kappa.setInputMask(_fromUtf8(""))
        self.Lattice_parameters____kappa.setMaxLength(256)
        self.Lattice_parameters____kappa.setObjectName(_fromUtf8("Lattice_parameters____kappa"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.Lattice_parameters____kappa)
        self.lbl0_59 = QtGui.QLabel(self.groupBox_4)
        self.lbl0_59.setObjectName(_fromUtf8("lbl0_59"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.lbl0_59)
        self.HMC_parameters____mu = QtGui.QLineEdit(self.groupBox_4)
        self.HMC_parameters____mu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.HMC_parameters____mu.setInputMask(_fromUtf8(""))
        self.HMC_parameters____mu.setMaxLength(256)
        self.HMC_parameters____mu.setObjectName(_fromUtf8("HMC_parameters____mu"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.HMC_parameters____mu)
        self.verticalLayout_3.addLayout(self.formLayout)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabLattice)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.lbl0_6 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_6.setObjectName(_fromUtf8("lbl0_6"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_6)
        self.Boundary_conditions____type = QtGui.QComboBox(self.groupBox_3)
        self.Boundary_conditions____type.setObjectName(_fromUtf8("Boundary_conditions____type"))
        self.Boundary_conditions____type.addItem(_fromUtf8(""))
        self.Boundary_conditions____type.addItem(_fromUtf8(""))
        self.Boundary_conditions____type.addItem(_fromUtf8(""))
        self.Boundary_conditions____type.addItem(_fromUtf8(""))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____type)
        self.verticalLayout_6.addLayout(self.formLayout_7)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_10 = QtGui.QFormLayout()
        self.formLayout_10.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_10.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_10.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.lbl0_79 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_79.setObjectName(_fromUtf8("lbl0_79"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_79)
        self.Boundary_conditions____cG = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____cG.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____cG.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____cG.setMaxLength(15)
        self.Boundary_conditions____cG.setObjectName(_fromUtf8("Boundary_conditions____cG"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____cG)
        self.lbl0_80 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_80.setObjectName(_fromUtf8("lbl0_80"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_80)
        self.Boundary_conditions____cF = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____cF.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____cF.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____cF.setMaxLength(15)
        self.Boundary_conditions____cF.setObjectName(_fromUtf8("Boundary_conditions____cF"))
        self.formLayout_10.setWidget(2, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____cF)
        self.lbl0_81 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_81.setObjectName(_fromUtf8("lbl0_81"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_81)
        self.Boundary_conditions____phi = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____phi.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____phi.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____phi.setMaxLength(15)
        self.Boundary_conditions____phi.setObjectName(_fromUtf8("Boundary_conditions____phi"))
        self.formLayout_10.setWidget(3, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____phi)
        self.lbl0_82 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_82.setObjectName(_fromUtf8("lbl0_82"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl0_82)
        self.horizontalLayout_3.addLayout(self.formLayout_10)
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_8.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.lbl0_39 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_39.setObjectName(_fromUtf8("lbl0_39"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_39)
        self.Boundary_conditions____cGprime = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____cGprime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____cGprime.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____cGprime.setMaxLength(15)
        self.Boundary_conditions____cGprime.setObjectName(_fromUtf8("Boundary_conditions____cGprime"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____cGprime)
        self.lbl0_40 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_40.setObjectName(_fromUtf8("lbl0_40"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_40)
        self.lbl0_41 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_41.setObjectName(_fromUtf8("lbl0_41"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_41)
        self.Boundary_conditions____cFprime = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____cFprime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____cFprime.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____cFprime.setMaxLength(15)
        self.Boundary_conditions____cFprime.setObjectName(_fromUtf8("Boundary_conditions____cFprime"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____cFprime)
        self.Boundary_conditions____phiprime = QtGui.QLineEdit(self.groupBox_3)
        self.Boundary_conditions____phiprime.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Boundary_conditions____phiprime.setInputMask(_fromUtf8(""))
        self.Boundary_conditions____phiprime.setMaxLength(15)
        self.Boundary_conditions____phiprime.setObjectName(_fromUtf8("Boundary_conditions____phiprime"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.Boundary_conditions____phiprime)
        self.lbl0_78 = QtGui.QLabel(self.groupBox_3)
        self.lbl0_78.setObjectName(_fromUtf8("lbl0_78"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl0_78)
        self.horizontalLayout_3.addLayout(self.formLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.tabMain.addTab(self.tabLattice, _fromUtf8(""))
        self.tabOther = QtGui.QWidget()
        self.tabOther.setObjectName(_fromUtf8("tabOther"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabOther)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupDir = QtGui.QGroupBox(self.tabOther)
        self.groupDir.setFlat(False)
        self.groupDir.setObjectName(_fromUtf8("groupDir"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupDir)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lbl0_5 = QtGui.QLabel(self.groupDir)
        self.lbl0_5.setObjectName(_fromUtf8("lbl0_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_5)
        self.Directories____log_dir = QtGui.QLineEdit(self.groupDir)
        self.Directories____log_dir.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Directories____log_dir.setInputMask(_fromUtf8(""))
        self.Directories____log_dir.setMaxLength(32767)
        self.Directories____log_dir.setObjectName(_fromUtf8("Directories____log_dir"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.Directories____log_dir)
        self.lbl0_9 = QtGui.QLabel(self.groupDir)
        self.lbl0_9.setObjectName(_fromUtf8("lbl0_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_9)
        self.Directories____dat_dir = QtGui.QLineEdit(self.groupDir)
        self.Directories____dat_dir.setObjectName(_fromUtf8("Directories____dat_dir"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.Directories____dat_dir)
        self.lbl0_10 = QtGui.QLabel(self.groupDir)
        self.lbl0_10.setObjectName(_fromUtf8("lbl0_10"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_10)
        self.lbl0_11 = QtGui.QLabel(self.groupDir)
        self.lbl0_11.setObjectName(_fromUtf8("lbl0_11"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_11)
        self.Directories____loc_dir = QtGui.QLineEdit(self.groupDir)
        self.Directories____loc_dir.setObjectName(_fromUtf8("Directories____loc_dir"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.Directories____loc_dir)
        self.Directories____cnfg_dir = QtGui.QLineEdit(self.groupDir)
        self.Directories____cnfg_dir.setObjectName(_fromUtf8("Directories____cnfg_dir"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.Directories____cnfg_dir)
        self.horizontalLayout_5.addLayout(self.formLayout_3)
        self.verticalLayout_4.addWidget(self.groupDir)
        self.groupBox_2 = QtGui.QGroupBox(self.tabOther)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lbl0_13 = QtGui.QLabel(self.groupBox_2)
        self.lbl0_13.setObjectName(_fromUtf8("lbl0_13"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_13)
        self.Random_number_generator____level = QtGui.QComboBox(self.groupBox_2)
        self.Random_number_generator____level.setObjectName(_fromUtf8("Random_number_generator____level"))
        self.Random_number_generator____level.addItem(_fromUtf8(""))
        self.Random_number_generator____level.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.Random_number_generator____level)
        self.lbl0_14 = QtGui.QLabel(self.groupBox_2)
        self.lbl0_14.setObjectName(_fromUtf8("lbl0_14"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_14)
        self.Random_number_generator____seed = QtGui.QLineEdit(self.groupBox_2)
        self.Random_number_generator____seed.setObjectName(_fromUtf8("Random_number_generator____seed"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.Random_number_generator____seed)
        self.horizontalLayout_6.addLayout(self.formLayout_4)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_5 = QtGui.QGroupBox(self.tabOther)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.lbl0_21 = QtGui.QLabel(self.groupBox_5)
        self.lbl0_21.setObjectName(_fromUtf8("lbl0_21"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_21)
        self.Wilson_flow____integrator = QtGui.QComboBox(self.groupBox_5)
        self.Wilson_flow____integrator.setObjectName(_fromUtf8("Wilson_flow____integrator"))
        self.Wilson_flow____integrator.addItem(_fromUtf8(""))
        self.Wilson_flow____integrator.addItem(_fromUtf8(""))
        self.Wilson_flow____integrator.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.Wilson_flow____integrator)
        self.lbl0_22 = QtGui.QLabel(self.groupBox_5)
        self.lbl0_22.setObjectName(_fromUtf8("lbl0_22"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_22)
        self.Wilson_flow____eps = QtGui.QLineEdit(self.groupBox_5)
        self.Wilson_flow____eps.setObjectName(_fromUtf8("Wilson_flow____eps"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.Wilson_flow____eps)
        self.lbl0_23 = QtGui.QLabel(self.groupBox_5)
        self.lbl0_23.setObjectName(_fromUtf8("lbl0_23"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_23)
        self.Wilson_flow____nstep = QtGui.QLineEdit(self.groupBox_5)
        self.Wilson_flow____nstep.setObjectName(_fromUtf8("Wilson_flow____nstep"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.Wilson_flow____nstep)
        self.lbl0_24 = QtGui.QLabel(self.groupBox_5)
        self.lbl0_24.setObjectName(_fromUtf8("lbl0_24"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_24)
        self.Wilson_flow____dnms = QtGui.QLineEdit(self.groupBox_5)
        self.Wilson_flow____dnms.setObjectName(_fromUtf8("Wilson_flow____dnms"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.Wilson_flow____dnms)
        self.horizontalLayout_4.addLayout(self.formLayout_6)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.tabMain.addTab(self.tabOther, _fromUtf8(""))
        self.tabSolvers = QtGui.QWidget()
        self.tabSolvers.setObjectName(_fromUtf8("tabSolvers"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.tabSolvers)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.groupBox_8 = QtGui.QGroupBox(self.tabSolvers)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.listSolvers = QtGui.QListWidget(self.groupBox_8)
        self.listSolvers.setEnabled(False)
        self.listSolvers.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listSolvers.setDragEnabled(True)
        self.listSolvers.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listSolvers.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listSolvers.setObjectName(_fromUtf8("listSolvers"))
        self.verticalLayout_5.addWidget(self.listSolvers)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.btnAddSolver = QtGui.QPushButton(self.groupBox_8)
        self.btnAddSolver.setObjectName(_fromUtf8("btnAddSolver"))
        self.horizontalLayout_14.addWidget(self.btnAddSolver)
        self.btnRemoveSolver = QtGui.QPushButton(self.groupBox_8)
        self.btnRemoveSolver.setEnabled(False)
        self.btnRemoveSolver.setObjectName(_fromUtf8("btnRemoveSolver"))
        self.horizontalLayout_14.addWidget(self.btnRemoveSolver)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_19.addWidget(self.groupBox_8)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.groupSolver = QtGui.QGroupBox(self.tabSolvers)
        self.groupSolver.setEnabled(False)
        self.groupSolver.setFlat(False)
        self.groupSolver.setObjectName(_fromUtf8("groupSolver"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupSolver)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setVerticalSpacing(6)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lbl0_15 = QtGui.QLabel(self.groupSolver)
        self.lbl0_15.setObjectName(_fromUtf8("lbl0_15"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_15)
        self.lblSolverIndex = QtGui.QLabel(self.groupSolver)
        self.lblSolverIndex.setObjectName(_fromUtf8("lblSolverIndex"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblSolverIndex)
        self.lbl0_3 = QtGui.QLabel(self.groupSolver)
        self.lbl0_3.setObjectName(_fromUtf8("lbl0_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_3)
        self.Solver____solver = QtGui.QComboBox(self.groupSolver)
        self.Solver____solver.setObjectName(_fromUtf8("Solver____solver"))
        self.Solver____solver.addItem(_fromUtf8(""))
        self.Solver____solver.addItem(_fromUtf8(""))
        self.Solver____solver.addItem(_fromUtf8(""))
        self.Solver____solver.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.Solver____solver)
        self.lblSolvernmx = QtGui.QLabel(self.groupSolver)
        self.lblSolvernmx.setObjectName(_fromUtf8("lblSolvernmx"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.lblSolvernmx)
        self.Solver____nmx = QtGui.QLineEdit(self.groupSolver)
        self.Solver____nmx.setAutoFillBackground(False)
        self.Solver____nmx.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Solver____nmx.setInputMask(_fromUtf8(""))
        self.Solver____nmx.setMaxLength(15)
        self.Solver____nmx.setObjectName(_fromUtf8("Solver____nmx"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.Solver____nmx)
        self.lbl0_18 = QtGui.QLabel(self.groupSolver)
        self.lbl0_18.setObjectName(_fromUtf8("lbl0_18"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_18)
        self.Solver____res = QtGui.QLineEdit(self.groupSolver)
        self.Solver____res.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Solver____res.setInputMask(_fromUtf8(""))
        self.Solver____res.setMaxLength(15)
        self.Solver____res.setObjectName(_fromUtf8("Solver____res"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.Solver____res)
        self.lbl0_30 = QtGui.QLabel(self.groupSolver)
        self.lbl0_30.setObjectName(_fromUtf8("lbl0_30"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl0_30)
        self.Solver____nkv = QtGui.QLineEdit(self.groupSolver)
        self.Solver____nkv.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Solver____nkv.setInputMask(_fromUtf8(""))
        self.Solver____nkv.setMaxLength(15)
        self.Solver____nkv.setObjectName(_fromUtf8("Solver____nkv"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.Solver____nkv)
        self.lbl0_31 = QtGui.QLabel(self.groupSolver)
        self.lbl0_31.setObjectName(_fromUtf8("lbl0_31"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl0_31)
        self.Solver____isolv = QtGui.QComboBox(self.groupSolver)
        self.Solver____isolv.setObjectName(_fromUtf8("Solver____isolv"))
        self.Solver____isolv.addItem(_fromUtf8(""))
        self.Solver____isolv.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.Solver____isolv)
        self.lbl0_32 = QtGui.QLabel(self.groupSolver)
        self.lbl0_32.setObjectName(_fromUtf8("lbl0_32"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl0_32)
        self.Solver____nmr = QtGui.QLineEdit(self.groupSolver)
        self.Solver____nmr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Solver____nmr.setInputMask(_fromUtf8(""))
        self.Solver____nmr.setMaxLength(15)
        self.Solver____nmr.setObjectName(_fromUtf8("Solver____nmr"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.Solver____nmr)
        self.lbl0_33 = QtGui.QLabel(self.groupSolver)
        self.lbl0_33.setObjectName(_fromUtf8("lbl0_33"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl0_33)
        self.Solver____ncy = QtGui.QLineEdit(self.groupSolver)
        self.Solver____ncy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Solver____ncy.setInputMask(_fromUtf8(""))
        self.Solver____ncy.setMaxLength(15)
        self.Solver____ncy.setObjectName(_fromUtf8("Solver____ncy"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.Solver____ncy)
        self.horizontalLayout_8.addLayout(self.formLayout_2)
        self.verticalLayout_14.addWidget(self.groupSolver)
        self.groupSolver_2 = QtGui.QGroupBox(self.tabSolvers)
        self.groupSolver_2.setFlat(False)
        self.groupSolver_2.setObjectName(_fromUtf8("groupSolver_2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupSolver_2)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.formLayout_16 = QtGui.QFormLayout()
        self.formLayout_16.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_16.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_16.setVerticalSpacing(6)
        self.formLayout_16.setObjectName(_fromUtf8("formLayout_16"))
        self.lblSolvernmx_3 = QtGui.QLabel(self.groupSolver_2)
        self.lblSolvernmx_3.setObjectName(_fromUtf8("lblSolvernmx_3"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblSolvernmx_3)
        self.SAP____bs = QtGui.QLineEdit(self.groupSolver_2)
        self.SAP____bs.setEnabled(False)
        self.SAP____bs.setAutoFillBackground(False)
        self.SAP____bs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.SAP____bs.setInputMask(_fromUtf8(""))
        self.SAP____bs.setMaxLength(15)
        self.SAP____bs.setObjectName(_fromUtf8("SAP____bs"))
        self.formLayout_16.setWidget(0, QtGui.QFormLayout.FieldRole, self.SAP____bs)
        self.horizontalLayout_10.addLayout(self.formLayout_16)
        self.verticalLayout_14.addWidget(self.groupSolver_2)
        self.horizontalLayout_19.addLayout(self.verticalLayout_14)
        self.tabMain.addTab(self.tabSolvers, _fromUtf8(""))
        self.tabRAT = QtGui.QWidget()
        self.tabRAT.setObjectName(_fromUtf8("tabRAT"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.tabRAT)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.groupBox_11 = QtGui.QGroupBox(self.tabRAT)
        self.groupBox_11.setFlat(False)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.listRAT = QtGui.QListWidget(self.groupBox_11)
        self.listRAT.setEnabled(False)
        self.listRAT.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listRAT.setDragEnabled(True)
        self.listRAT.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listRAT.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listRAT.setObjectName(_fromUtf8("listRAT"))
        self.verticalLayout_9.addWidget(self.listRAT)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.btnAddRAT = QtGui.QPushButton(self.groupBox_11)
        self.btnAddRAT.setObjectName(_fromUtf8("btnAddRAT"))
        self.horizontalLayout_15.addWidget(self.btnAddRAT)
        self.btnRemoveRAT = QtGui.QPushButton(self.groupBox_11)
        self.btnRemoveRAT.setEnabled(False)
        self.btnRemoveRAT.setObjectName(_fromUtf8("btnRemoveRAT"))
        self.horizontalLayout_15.addWidget(self.btnRemoveRAT)
        self.verticalLayout_9.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_13.addWidget(self.groupBox_11)
        self.groupRAT = QtGui.QGroupBox(self.tabRAT)
        self.groupRAT.setEnabled(False)
        self.groupRAT.setFlat(False)
        self.groupRAT.setObjectName(_fromUtf8("groupRAT"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupRAT)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.formLayout_12 = QtGui.QFormLayout()
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_12.setVerticalSpacing(6)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.lbl0_16 = QtGui.QLabel(self.groupRAT)
        self.lbl0_16.setObjectName(_fromUtf8("lbl0_16"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_16)
        self.lblRATIndex = QtGui.QLabel(self.groupRAT)
        self.lblRATIndex.setObjectName(_fromUtf8("lblRATIndex"))
        self.formLayout_12.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblRATIndex)
        self.lblSolvernmx_2 = QtGui.QLabel(self.groupRAT)
        self.lblSolvernmx_2.setObjectName(_fromUtf8("lblSolvernmx_2"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.LabelRole, self.lblSolvernmx_2)
        self.Rational____degree = QtGui.QLineEdit(self.groupRAT)
        self.Rational____degree.setAutoFillBackground(False)
        self.Rational____degree.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Rational____degree.setInputMask(_fromUtf8(""))
        self.Rational____degree.setMaxLength(15)
        self.Rational____degree.setObjectName(_fromUtf8("Rational____degree"))
        self.formLayout_12.setWidget(1, QtGui.QFormLayout.FieldRole, self.Rational____degree)
        self.lbl0_29 = QtGui.QLabel(self.groupRAT)
        self.lbl0_29.setObjectName(_fromUtf8("lbl0_29"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_29)
        self.Rational____range = QtGui.QLineEdit(self.groupRAT)
        self.Rational____range.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Rational____range.setInputMask(_fromUtf8(""))
        self.Rational____range.setMaxLength(15)
        self.Rational____range.setObjectName(_fromUtf8("Rational____range"))
        self.formLayout_12.setWidget(2, QtGui.QFormLayout.FieldRole, self.Rational____range)
        self.horizontalLayout_12.addLayout(self.formLayout_12)
        self.horizontalLayout_13.addWidget(self.groupRAT)
        self.tabMain.addTab(self.tabRAT, _fromUtf8(""))
        self.tabDeflation = QtGui.QWidget()
        self.tabDeflation.setObjectName(_fromUtf8("tabDeflation"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.tabDeflation)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.groupDFLsubspace = QtGui.QGroupBox(self.tabDeflation)
        self.groupDFLsubspace.setEnabled(False)
        self.groupDFLsubspace.setFlat(False)
        self.groupDFLsubspace.setObjectName(_fromUtf8("groupDFLsubspace"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupDFLsubspace)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.formLayout_13 = QtGui.QFormLayout()
        self.formLayout_13.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_13.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_13.setVerticalSpacing(6)
        self.formLayout_13.setObjectName(_fromUtf8("formLayout_13"))
        self.lbl0_55 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_55.setObjectName(_fromUtf8("lbl0_55"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_55)
        self.Deflation_subspace____bs = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace____bs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace____bs.setInputMask(_fromUtf8(""))
        self.Deflation_subspace____bs.setMaxLength(256)
        self.Deflation_subspace____bs.setObjectName(_fromUtf8("Deflation_subspace____bs"))
        self.formLayout_13.setWidget(0, QtGui.QFormLayout.FieldRole, self.Deflation_subspace____bs)
        self.lbl0_8 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_8.setObjectName(_fromUtf8("lbl0_8"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_8)
        self.Deflation_subspace____Ns = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace____Ns.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace____Ns.setInputMask(_fromUtf8(""))
        self.Deflation_subspace____Ns.setMaxLength(256)
        self.Deflation_subspace____Ns.setObjectName(_fromUtf8("Deflation_subspace____Ns"))
        self.formLayout_13.setWidget(1, QtGui.QFormLayout.FieldRole, self.Deflation_subspace____Ns)
        self.lbl0_68 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_68.setObjectName(_fromUtf8("lbl0_68"))
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_68)
        self.Deflation_subspace_generation____kappa = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace_generation____kappa.setAutoFillBackground(False)
        self.Deflation_subspace_generation____kappa.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace_generation____kappa.setInputMask(_fromUtf8(""))
        self.Deflation_subspace_generation____kappa.setMaxLength(128)
        self.Deflation_subspace_generation____kappa.setObjectName(_fromUtf8("Deflation_subspace_generation____kappa"))
        self.formLayout_13.setWidget(2, QtGui.QFormLayout.FieldRole, self.Deflation_subspace_generation____kappa)
        self.lbl0_69 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_69.setObjectName(_fromUtf8("lbl0_69"))
        self.formLayout_13.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_69)
        self.Deflation_subspace_generation____mu = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace_generation____mu.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace_generation____mu.setInputMask(_fromUtf8(""))
        self.Deflation_subspace_generation____mu.setMaxLength(128)
        self.Deflation_subspace_generation____mu.setObjectName(_fromUtf8("Deflation_subspace_generation____mu"))
        self.formLayout_13.setWidget(3, QtGui.QFormLayout.FieldRole, self.Deflation_subspace_generation____mu)
        self.lbl0_70 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_70.setObjectName(_fromUtf8("lbl0_70"))
        self.formLayout_13.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl0_70)
        self.Deflation_subspace_generation____ninv = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace_generation____ninv.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace_generation____ninv.setInputMask(_fromUtf8(""))
        self.Deflation_subspace_generation____ninv.setMaxLength(128)
        self.Deflation_subspace_generation____ninv.setObjectName(_fromUtf8("Deflation_subspace_generation____ninv"))
        self.formLayout_13.setWidget(4, QtGui.QFormLayout.FieldRole, self.Deflation_subspace_generation____ninv)
        self.lbl0_83 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_83.setObjectName(_fromUtf8("lbl0_83"))
        self.formLayout_13.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl0_83)
        self.Deflation_subspace_generation____nmr = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace_generation____nmr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace_generation____nmr.setInputMask(_fromUtf8(""))
        self.Deflation_subspace_generation____nmr.setMaxLength(128)
        self.Deflation_subspace_generation____nmr.setObjectName(_fromUtf8("Deflation_subspace_generation____nmr"))
        self.formLayout_13.setWidget(5, QtGui.QFormLayout.FieldRole, self.Deflation_subspace_generation____nmr)
        self.lbl0_84 = QtGui.QLabel(self.groupDFLsubspace)
        self.lbl0_84.setObjectName(_fromUtf8("lbl0_84"))
        self.formLayout_13.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl0_84)
        self.Deflation_subspace_generation____ncy = QtGui.QLineEdit(self.groupDFLsubspace)
        self.Deflation_subspace_generation____ncy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_subspace_generation____ncy.setInputMask(_fromUtf8(""))
        self.Deflation_subspace_generation____ncy.setMaxLength(128)
        self.Deflation_subspace_generation____ncy.setObjectName(_fromUtf8("Deflation_subspace_generation____ncy"))
        self.formLayout_13.setWidget(6, QtGui.QFormLayout.FieldRole, self.Deflation_subspace_generation____ncy)
        self.verticalLayout_10.addLayout(self.formLayout_13)
        self.verticalLayout_13.addWidget(self.groupDFLsubspace)
        self.groupDFLprojection = QtGui.QGroupBox(self.tabDeflation)
        self.groupDFLprojection.setEnabled(False)
        self.groupDFLprojection.setFlat(False)
        self.groupDFLprojection.setObjectName(_fromUtf8("groupDFLprojection"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupDFLprojection)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.formLayout_14 = QtGui.QFormLayout()
        self.formLayout_14.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_14.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_14.setVerticalSpacing(6)
        self.formLayout_14.setObjectName(_fromUtf8("formLayout_14"))
        self.lbl0_85 = QtGui.QLabel(self.groupDFLprojection)
        self.lbl0_85.setObjectName(_fromUtf8("lbl0_85"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_85)
        self.Deflation_projection____nkv = QtGui.QLineEdit(self.groupDFLprojection)
        self.Deflation_projection____nkv.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_projection____nkv.setInputMask(_fromUtf8(""))
        self.Deflation_projection____nkv.setMaxLength(256)
        self.Deflation_projection____nkv.setObjectName(_fromUtf8("Deflation_projection____nkv"))
        self.formLayout_14.setWidget(0, QtGui.QFormLayout.FieldRole, self.Deflation_projection____nkv)
        self.lbl0_86 = QtGui.QLabel(self.groupDFLprojection)
        self.lbl0_86.setObjectName(_fromUtf8("lbl0_86"))
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_86)
        self.Deflation_projection____nmx = QtGui.QLineEdit(self.groupDFLprojection)
        self.Deflation_projection____nmx.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_projection____nmx.setInputMask(_fromUtf8(""))
        self.Deflation_projection____nmx.setMaxLength(256)
        self.Deflation_projection____nmx.setObjectName(_fromUtf8("Deflation_projection____nmx"))
        self.formLayout_14.setWidget(1, QtGui.QFormLayout.FieldRole, self.Deflation_projection____nmx)
        self.lbl0_87 = QtGui.QLabel(self.groupDFLprojection)
        self.lbl0_87.setObjectName(_fromUtf8("lbl0_87"))
        self.formLayout_14.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_87)
        self.Deflation_projection____res = QtGui.QLineEdit(self.groupDFLprojection)
        self.Deflation_projection____res.setAutoFillBackground(False)
        self.Deflation_projection____res.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_projection____res.setInputMask(_fromUtf8(""))
        self.Deflation_projection____res.setMaxLength(128)
        self.Deflation_projection____res.setObjectName(_fromUtf8("Deflation_projection____res"))
        self.formLayout_14.setWidget(2, QtGui.QFormLayout.FieldRole, self.Deflation_projection____res)
        self.verticalLayout_11.addLayout(self.formLayout_14)
        self.verticalLayout_13.addWidget(self.groupDFLprojection)
        self.groupDFLupdate = QtGui.QGroupBox(self.tabDeflation)
        self.groupDFLupdate.setEnabled(False)
        self.groupDFLupdate.setFlat(False)
        self.groupDFLupdate.setObjectName(_fromUtf8("groupDFLupdate"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.groupDFLupdate)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.formLayout_15 = QtGui.QFormLayout()
        self.formLayout_15.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_15.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_15.setVerticalSpacing(6)
        self.formLayout_15.setObjectName(_fromUtf8("formLayout_15"))
        self.lbl0_88 = QtGui.QLabel(self.groupDFLupdate)
        self.lbl0_88.setObjectName(_fromUtf8("lbl0_88"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_88)
        self.Deflation_update_scheme____dtau = QtGui.QLineEdit(self.groupDFLupdate)
        self.Deflation_update_scheme____dtau.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_update_scheme____dtau.setInputMask(_fromUtf8(""))
        self.Deflation_update_scheme____dtau.setMaxLength(256)
        self.Deflation_update_scheme____dtau.setObjectName(_fromUtf8("Deflation_update_scheme____dtau"))
        self.formLayout_15.setWidget(0, QtGui.QFormLayout.FieldRole, self.Deflation_update_scheme____dtau)
        self.lbl0_89 = QtGui.QLabel(self.groupDFLupdate)
        self.lbl0_89.setObjectName(_fromUtf8("lbl0_89"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_89)
        self.Deflation_update_scheme____nsm = QtGui.QLineEdit(self.groupDFLupdate)
        self.Deflation_update_scheme____nsm.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Deflation_update_scheme____nsm.setInputMask(_fromUtf8(""))
        self.Deflation_update_scheme____nsm.setMaxLength(256)
        self.Deflation_update_scheme____nsm.setObjectName(_fromUtf8("Deflation_update_scheme____nsm"))
        self.formLayout_15.setWidget(1, QtGui.QFormLayout.FieldRole, self.Deflation_update_scheme____nsm)
        self.verticalLayout_12.addLayout(self.formLayout_15)
        self.verticalLayout_13.addWidget(self.groupDFLupdate)
        self.tabMain.addTab(self.tabDeflation, _fromUtf8(""))
        self.tabAction = QtGui.QWidget()
        self.tabAction.setObjectName(_fromUtf8("tabAction"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.tabAction)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.groupBox_10 = QtGui.QGroupBox(self.tabAction)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.listActions = QtGui.QListWidget(self.groupBox_10)
        self.listActions.setEnabled(False)
        self.listActions.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listActions.setDragEnabled(True)
        self.listActions.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.listActions.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listActions.setObjectName(_fromUtf8("listActions"))
        self.verticalLayout_8.addWidget(self.listActions)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.btnAddAction = QtGui.QPushButton(self.groupBox_10)
        self.btnAddAction.setObjectName(_fromUtf8("btnAddAction"))
        self.horizontalLayout_16.addWidget(self.btnAddAction)
        self.btnRemoveAction = QtGui.QPushButton(self.groupBox_10)
        self.btnRemoveAction.setEnabled(False)
        self.btnRemoveAction.setObjectName(_fromUtf8("btnRemoveAction"))
        self.horizontalLayout_16.addWidget(self.btnRemoveAction)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17.addWidget(self.groupBox_10)
        self.groupAction = QtGui.QGroupBox(self.tabAction)
        self.groupAction.setEnabled(False)
        self.groupAction.setFlat(False)
        self.groupAction.setObjectName(_fromUtf8("groupAction"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupAction)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.formLayout_11 = QtGui.QFormLayout()
        self.formLayout_11.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_11.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_11.setVerticalSpacing(6)
        self.formLayout_11.setObjectName(_fromUtf8("formLayout_11"))
        self.lbl0_28 = QtGui.QLabel(self.groupAction)
        self.lbl0_28.setObjectName(_fromUtf8("lbl0_28"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl0_28)
        self.lblActionIndex = QtGui.QLabel(self.groupAction)
        self.lblActionIndex.setObjectName(_fromUtf8("lblActionIndex"))
        self.formLayout_11.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblActionIndex)
        self.lbl0_7 = QtGui.QLabel(self.groupAction)
        self.lbl0_7.setObjectName(_fromUtf8("lbl0_7"))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl0_7)
        self.Action____action = QtGui.QComboBox(self.groupAction)
        self.Action____action.setObjectName(_fromUtf8("Action____action"))
        self.Action____action.addItem(_fromUtf8(""))
        self.Action____action.addItem(_fromUtf8(""))
        self.Action____action.addItem(_fromUtf8(""))
        self.Action____action.addItem(_fromUtf8(""))
        self.Action____action.addItem(_fromUtf8(""))
        self.Action____action.addItem(_fromUtf8(""))
        self.formLayout_11.setWidget(1, QtGui.QFormLayout.FieldRole, self.Action____action)
        self.lbl0_56 = QtGui.QLabel(self.groupAction)
        self.lbl0_56.setObjectName(_fromUtf8("lbl0_56"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl0_56)
        self.Action____im0 = QtGui.QComboBox(self.groupAction)
        self.Action____im0.setObjectName(_fromUtf8("Action____im0"))
        self.formLayout_11.setWidget(2, QtGui.QFormLayout.FieldRole, self.Action____im0)
        self.lbl0_57 = QtGui.QLabel(self.groupAction)
        self.lbl0_57.setObjectName(_fromUtf8("lbl0_57"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.LabelRole, self.lbl0_57)
        self.Action____imuX0 = QtGui.QComboBox(self.groupAction)
        self.Action____imuX0.setObjectName(_fromUtf8("Action____imuX0"))
        self.formLayout_11.setWidget(3, QtGui.QFormLayout.FieldRole, self.Action____imuX0)
        self.lbl0_60 = QtGui.QLabel(self.groupAction)
        self.lbl0_60.setObjectName(_fromUtf8("lbl0_60"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.LabelRole, self.lbl0_60)
        self.Action____ispX0 = QtGui.QComboBox(self.groupAction)
        self.Action____ispX0.setObjectName(_fromUtf8("Action____ispX0"))
        self.formLayout_11.setWidget(4, QtGui.QFormLayout.FieldRole, self.Action____ispX0)
        self.lbl0_58 = QtGui.QLabel(self.groupAction)
        self.lbl0_58.setObjectName(_fromUtf8("lbl0_58"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.LabelRole, self.lbl0_58)
        self.Action____imuX1 = QtGui.QComboBox(self.groupAction)
        self.Action____imuX1.setObjectName(_fromUtf8("Action____imuX1"))
        self.formLayout_11.setWidget(5, QtGui.QFormLayout.FieldRole, self.Action____imuX1)
        self.lbl0_61 = QtGui.QLabel(self.groupAction)
        self.lbl0_61.setObjectName(_fromUtf8("lbl0_61"))
        self.formLayout_11.setWidget(6, QtGui.QFormLayout.LabelRole, self.lbl0_61)
        self.Action____ispX1 = QtGui.QComboBox(self.groupAction)
        self.Action____ispX1.setObjectName(_fromUtf8("Action____ispX1"))
        self.formLayout_11.setWidget(6, QtGui.QFormLayout.FieldRole, self.Action____ispX1)
        self.lbl0_62 = QtGui.QLabel(self.groupAction)
        self.lbl0_62.setObjectName(_fromUtf8("lbl0_62"))
        self.formLayout_11.setWidget(7, QtGui.QFormLayout.LabelRole, self.lbl0_62)
        self.Action____iratX0 = QtGui.QComboBox(self.groupAction)
        self.Action____iratX0.setObjectName(_fromUtf8("Action____iratX0"))
        self.formLayout_11.setWidget(7, QtGui.QFormLayout.FieldRole, self.Action____iratX0)
        self.lbl0_63 = QtGui.QLabel(self.groupAction)
        self.lbl0_63.setObjectName(_fromUtf8("lbl0_63"))
        self.formLayout_11.setWidget(8, QtGui.QFormLayout.LabelRole, self.lbl0_63)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.lbl0_65 = QtGui.QLabel(self.groupAction)
        self.lbl0_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl0_65.setObjectName(_fromUtf8("lbl0_65"))
        self.horizontalLayout_7.addWidget(self.lbl0_65)
        self.Action____iratX1 = QtGui.QComboBox(self.groupAction)
        self.Action____iratX1.setObjectName(_fromUtf8("Action____iratX1"))
        self.horizontalLayout_7.addWidget(self.Action____iratX1)
        self.lbl0_64 = QtGui.QLabel(self.groupAction)
        self.lbl0_64.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl0_64.setObjectName(_fromUtf8("lbl0_64"))
        self.horizontalLayout_7.addWidget(self.lbl0_64)
        self.Action____iratX2 = QtGui.QComboBox(self.groupAction)
        self.Action____iratX2.setObjectName(_fromUtf8("Action____iratX2"))
        self.horizontalLayout_7.addWidget(self.Action____iratX2)
        self.formLayout_11.setLayout(8, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.lbl0_66 = QtGui.QLabel(self.groupAction)
        self.lbl0_66.setObjectName(_fromUtf8("lbl0_66"))
        self.formLayout_11.setWidget(9, QtGui.QFormLayout.LabelRole, self.lbl0_66)
        self.Force____isp = QtGui.QComboBox(self.groupAction)
        self.Force____isp.setObjectName(_fromUtf8("Force____isp"))
        self.formLayout_11.setWidget(9, QtGui.QFormLayout.FieldRole, self.Force____isp)
        self.lbl0_67 = QtGui.QLabel(self.groupAction)
        self.lbl0_67.setObjectName(_fromUtf8("lbl0_67"))
        self.formLayout_11.setWidget(10, QtGui.QFormLayout.LabelRole, self.lbl0_67)
        self.Force____ncr = QtGui.QLineEdit(self.groupAction)
        self.Force____ncr.setAutoFillBackground(False)
        self.Force____ncr.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Force____ncr.setInputMask(_fromUtf8(""))
        self.Force____ncr.setMaxLength(15)
        self.Force____ncr.setObjectName(_fromUtf8("Force____ncr"))
        self.formLayout_11.setWidget(10, QtGui.QFormLayout.FieldRole, self.Force____ncr)
        self.horizontalLayout_11.addLayout(self.formLayout_11)
        self.horizontalLayout_17.addWidget(self.groupAction)
        self.tabMain.addTab(self.tabAction, _fromUtf8(""))
        self.tabMDint = QtGui.QWidget()
        self.tabMDint.setObjectName(_fromUtf8("tabMDint"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabMDint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl0_35 = QtGui.QLabel(self.tabMDint)
        self.lbl0_35.setObjectName(_fromUtf8("lbl0_35"))
        self.gridLayout.addWidget(self.lbl0_35, 1, 0, 1, 1)
        self.lbl0_38 = QtGui.QLabel(self.tabMDint)
        self.lbl0_38.setObjectName(_fromUtf8("lbl0_38"))
        self.gridLayout.addWidget(self.lbl0_38, 4, 0, 1, 1)
        self.lbl0_37 = QtGui.QLabel(self.tabMDint)
        self.lbl0_37.setObjectName(_fromUtf8("lbl0_37"))
        self.gridLayout.addWidget(self.lbl0_37, 3, 0, 1, 1)
        self.lbl0_36 = QtGui.QLabel(self.tabMDint)
        self.lbl0_36.setObjectName(_fromUtf8("lbl0_36"))
        self.gridLayout.addWidget(self.lbl0_36, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.tabMDint)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.btnAddIntLevel = QtGui.QPushButton(self.tabMDint)
        self.btnAddIntLevel.setObjectName(_fromUtf8("btnAddIntLevel"))
        self.horizontalLayout_9.addWidget(self.btnAddIntLevel)
        self.btnRemoveIntLevel = QtGui.QPushButton(self.tabMDint)
        self.btnRemoveIntLevel.setEnabled(False)
        self.btnRemoveIntLevel.setObjectName(_fromUtf8("btnRemoveIntLevel"))
        self.horizontalLayout_9.addWidget(self.btnRemoveIntLevel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.tabMain.addTab(self.tabMDint, _fromUtf8(""))
        self.tabInputFile = QtGui.QWidget()
        self.tabInputFile.setObjectName(_fromUtf8("tabInputFile"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.tabInputFile)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.txtInputFile = QtGui.QPlainTextEdit(self.tabInputFile)
        self.txtInputFile.setAcceptDrops(False)
        self.txtInputFile.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.txtInputFile.setReadOnly(True)
        self.txtInputFile.setTabStopWidth(50)
        self.txtInputFile.setObjectName(_fromUtf8("txtInputFile"))
        self.verticalLayout_15.addWidget(self.txtInputFile)
        self.groupSort = QtGui.QGroupBox(self.tabInputFile)
        self.groupSort.setObjectName(_fromUtf8("groupSort"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupSort)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioSortDefault = QtGui.QRadioButton(self.groupSort)
        self.radioSortDefault.setChecked(True)
        self.radioSortDefault.setObjectName(_fromUtf8("radioSortDefault"))
        self.horizontalLayout_2.addWidget(self.radioSortDefault)
        self.radioSortAlpha = QtGui.QRadioButton(self.groupSort)
        self.radioSortAlpha.setObjectName(_fromUtf8("radioSortAlpha"))
        self.horizontalLayout_2.addWidget(self.radioSortAlpha)
        self.radioSortOriginal = QtGui.QRadioButton(self.groupSort)
        self.radioSortOriginal.setObjectName(_fromUtf8("radioSortOriginal"))
        self.horizontalLayout_2.addWidget(self.radioSortOriginal)
        self.verticalLayout_15.addWidget(self.groupSort)
        self.tabMain.addTab(self.tabInputFile, _fromUtf8(""))
        self.horizontalLayout_18.addWidget(self.tabMain)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnOpen = QtGui.QPushButton(Form)
        self.btnOpen.setAutoDefault(False)
        self.btnOpen.setFlat(False)
        self.btnOpen.setObjectName(_fromUtf8("btnOpen"))
        self.horizontalLayout.addWidget(self.btnOpen)
        self.btnSave = QtGui.QPushButton(Form)
        self.btnSave.setAutoDefault(False)
        self.btnSave.setFlat(False)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout.addWidget(self.btnSave)
        self.btnHelp = QtGui.QPushButton(Form)
        self.btnHelp.setAutoDefault(False)
        self.btnHelp.setFlat(False)
        self.btnHelp.setObjectName(_fromUtf8("btnHelp"))
        self.horizontalLayout.addWidget(self.btnHelp)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.tabMain.setCurrentIndex(0)
        self.Lattice_parameters____c0.setCurrentIndex(0)
        self.Boundary_conditions____type.setCurrentIndex(2)
        self.Wilson_flow____integrator.setCurrentIndex(2)
        self.Solver____solver.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "openQCD Input File Editor", None))
        self.groupBox_4.setTitle(_translate("Form", " Run Parameters", None))
        self.lbl0_12.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_12.setText(_translate("Form", "Run name:", None))
        self.Run_name____name.setText(_translate("Form", "default", None))
        self.lbl0_2.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_2.setText(_translate("Form", "Gauge action c_0:", None))
        self.Lattice_parameters____c0.setItemText(0, _translate("Form", "1.0 [Wilson plaquette]", None))
        self.Lattice_parameters____c0.setItemText(1, _translate("Form", "1.6666667 [Tree-level Symanzik Improved]", None))
        self.Lattice_parameters____c0.setItemText(2, _translate("Form", "3.648 [Iwasaki]", None))
        self.lbl0_4.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_4.setText(_translate("Form", "Beta:", None))
        self.Lattice_parameters____beta.setText(_translate("Form", "6.00", None))
        self.lbl0_17.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_17.setText(_translate("Form", "Trajectory Length:", None))
        self.HMC_parameters____tau.setText(_translate("Form", "3.00", None))
        self.lbl0_19.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_19.setText(_translate("Form", "Thermalisation Trajectories:", None))
        self.MD_trajectories____nth.setText(_translate("Form", "320", None))
        self.lbl0_20.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_20.setText(_translate("Form", "Total Trajectories:", None))
        self.MD_trajectories____ntr.setText(_translate("Form", "3200", None))
        self.lbl0_25.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_25.setText(_translate("Form", "Log every:", None))
        self.MD_trajectories____dtr_log.setText(_translate("Form", "4", None))
        self.lbl0_26.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_26.setText(_translate("Form", "Measure every:", None))
        self.MD_trajectories____dtr_ms.setText(_translate("Form", "4", None))
        self.lbl0_27.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_27.setText(_translate("Form", "Save config every:", None))
        self.MD_trajectories____dtr_cnfg.setText(_translate("Form", "20", None))
        self.lbl0_34.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_34.setText(_translate("Form", "Kappa values:", None))
        self.Lattice_parameters____kappa.setText(_translate("Form", "0.160 0.165", None))
        self.lbl0_59.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_59.setText(_translate("Form", "Twisted mass values:", None))
        self.HMC_parameters____mu.setText(_translate("Form", "0.1 0.2", None))
        self.groupBox_3.setTitle(_translate("Form", "Boundary Conditions", None))
        self.lbl0_6.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_6.setText(_translate("Form", "Boundary Conditions:", None))
        self.Boundary_conditions____type.setItemText(0, _translate("Form", "0 [Open]", None))
        self.Boundary_conditions____type.setItemText(1, _translate("Form", "1 [Schrodinger Functional]", None))
        self.Boundary_conditions____type.setItemText(2, _translate("Form", "2 [Open--Schrodinger Functional]", None))
        self.Boundary_conditions____type.setItemText(3, _translate("Form", "3 [Periodic]", None))
        self.lbl0_79.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_79.setText(_translate("Form", "cG:", None))
        self.Boundary_conditions____cG.setText(_translate("Form", "1.0", None))
        self.lbl0_80.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_80.setText(_translate("Form", "cF:", None))
        self.Boundary_conditions____cF.setText(_translate("Form", "1.0", None))
        self.lbl0_81.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_81.setText(_translate("Form", "phi:", None))
        self.Boundary_conditions____phi.setText(_translate("Form", "1.57 0.00", None))
        self.lbl0_82.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_82.setText(_translate("Form", "t=0", None))
        self.lbl0_39.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_39.setText(_translate("Form", "cG\':", None))
        self.Boundary_conditions____cGprime.setText(_translate("Form", "1.0", None))
        self.lbl0_40.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_40.setText(_translate("Form", "cF\':", None))
        self.lbl0_41.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_41.setText(_translate("Form", "phi\':", None))
        self.Boundary_conditions____cFprime.setText(_translate("Form", "1.0", None))
        self.Boundary_conditions____phiprime.setText(_translate("Form", "1.57 0.00", None))
        self.lbl0_78.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_78.setText(_translate("Form", "t=T", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabLattice), _translate("Form", "Lattice Params", None))
        self.groupDir.setTitle(_translate("Form", "Directories", None))
        self.lbl0_5.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_5.setText(_translate("Form", "Log dir:", None))
        self.Directories____log_dir.setText(_translate("Form", "log", None))
        self.lbl0_9.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_9.setText(_translate("Form", "Data dir:", None))
        self.Directories____dat_dir.setText(_translate("Form", "dat", None))
        self.lbl0_10.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_10.setText(_translate("Form", "Loc dir:", None))
        self.lbl0_11.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_11.setText(_translate("Form", "Cnfg dir:", None))
        self.Directories____loc_dir.setText(_translate("Form", "loc", None))
        self.Directories____cnfg_dir.setText(_translate("Form", "cnfg", None))
        self.groupBox_2.setTitle(_translate("Form", "Random number generator", None))
        self.lbl0_13.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_13.setText(_translate("Form", "Level:", None))
        self.Random_number_generator____level.setItemText(0, _translate("Form", "0", None))
        self.Random_number_generator____level.setItemText(1, _translate("Form", "1", None))
        self.lbl0_14.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_14.setText(_translate("Form", "Seed:", None))
        self.Random_number_generator____seed.setText(_translate("Form", "73099", None))
        self.groupBox_5.setTitle(_translate("Form", "Wilson Flow Measurements", None))
        self.lbl0_21.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_21.setText(_translate("Form", "Integrator:", None))
        self.Wilson_flow____integrator.setItemText(0, _translate("Form", "EULER [1st order Euler]", None))
        self.Wilson_flow____integrator.setItemText(1, _translate("Form", "RK2 [2nd order Runge-Kutta]", None))
        self.Wilson_flow____integrator.setItemText(2, _translate("Form", "RK3 [3rd order Runge-Kutta]", None))
        self.lbl0_22.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_22.setText(_translate("Form", "Epsilon:", None))
        self.Wilson_flow____eps.setText(_translate("Form", "0.01", None))
        self.lbl0_23.setToolTip(_translate("Form", "Number of integration steps per trajectory", None))
        self.lbl0_23.setText(_translate("Form", "Steps:", None))
        self.Wilson_flow____nstep.setText(_translate("Form", "100", None))
        self.lbl0_24.setToolTip(_translate("Form", "Number of integration steps per trajectory", None))
        self.lbl0_24.setText(_translate("Form", "Measure every:", None))
        self.Wilson_flow____dnms.setText(_translate("Form", "10", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabOther), _translate("Form", "Other Params", None))
        self.groupBox_8.setTitle(_translate("Form", "Solvers", None))
        self.listSolvers.setSortingEnabled(False)
        self.btnAddSolver.setText(_translate("Form", "Add Solver", None))
        self.btnRemoveSolver.setText(_translate("Form", "Remove Solver", None))
        self.groupSolver.setTitle(_translate("Form", "Solver Parameters", None))
        self.lbl0_15.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_15.setText(_translate("Form", "Solver Index:", None))
        self.lblSolverIndex.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblSolverIndex.setText(_translate("Form", "0", None))
        self.lbl0_3.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_3.setText(_translate("Form", "Solver:", None))
        self.Solver____solver.setItemText(0, _translate("Form", "CGNE", None))
        self.Solver____solver.setItemText(1, _translate("Form", "MSCG", None))
        self.Solver____solver.setItemText(2, _translate("Form", "SAP_GCR", None))
        self.Solver____solver.setItemText(3, _translate("Form", "DFL_SAP_GCR", None))
        self.lblSolvernmx.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblSolvernmx.setText(_translate("Form", "Max CG Iterations/Krylov vectors:", None))
        self.Solver____nmx.setText(_translate("Form", "128", None))
        self.lbl0_18.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_18.setText(_translate("Form", "Max Relative Residue:", None))
        self.Solver____res.setText(_translate("Form", "1.e-10", None))
        self.lbl0_30.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_30.setText(_translate("Form", "Max Krylov vectors before restart:", None))
        self.Solver____nkv.setText(_translate("Form", "24", None))
        self.lbl0_31.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_31.setText(_translate("Form", "Block Solver:", None))
        self.Solver____isolv.setItemText(0, _translate("Form", "0 [plain MinRes]", None))
        self.Solver____isolv.setItemText(1, _translate("Form", "1 [eo-preconditioned MinRes]", None))
        self.lbl0_32.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_32.setText(_translate("Form", "Block Solver Iterations:", None))
        self.Solver____nmr.setText(_translate("Form", "4", None))
        self.lbl0_33.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_33.setText(_translate("Form", "Number of SAP cycles:", None))
        self.Solver____ncy.setText(_translate("Form", "4", None))
        self.groupSolver_2.setTitle(_translate("Form", "SAP blocksize", None))
        self.lblSolvernmx_3.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblSolvernmx_3.setText(_translate("Form", "SAP block size (L0 L1 L2 L3):", None))
        self.SAP____bs.setText(_translate("Form", "4 4 4 4", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabSolvers), _translate("Form", "Solvers", None))
        self.groupBox_11.setTitle(_translate("Form", "Rational Approximations", None))
        self.listRAT.setSortingEnabled(False)
        self.btnAddRAT.setText(_translate("Form", "Add Rational Approx", None))
        self.btnRemoveRAT.setText(_translate("Form", "Remove Rational Approx", None))
        self.groupRAT.setTitle(_translate("Form", "Rational Approximation Parameters", None))
        self.lbl0_16.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_16.setText(_translate("Form", "Rational Approximation Index:", None))
        self.lblRATIndex.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblRATIndex.setText(_translate("Form", "0", None))
        self.lblSolvernmx_2.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblSolvernmx_2.setText(_translate("Form", "Degree:", None))
        self.Rational____degree.setText(_translate("Form", "10", None))
        self.lbl0_29.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_29.setText(_translate("Form", "Range (lower upper):", None))
        self.Rational____range.setText(_translate("Form", "1.e-3 6.10", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabRAT), _translate("Form", "Rational Approxs", None))
        self.groupDFLsubspace.setTitle(_translate("Form", "Deflation Subspace", None))
        self.lbl0_55.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_55.setText(_translate("Form", "Block size (L0 L1 L2 L3):", None))
        self.Deflation_subspace____bs.setText(_translate("Form", "4 4 4 4", None))
        self.lbl0_8.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_8.setText(_translate("Form", "Modes per block:", None))
        self.Deflation_subspace____Ns.setText(_translate("Form", "20", None))
        self.lbl0_68.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_68.setText(_translate("Form", "Kappa:", None))
        self.Deflation_subspace_generation____kappa.setText(_translate("Form", "0.135", None))
        self.lbl0_69.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_69.setText(_translate("Form", "Twisted Mass:", None))
        self.Deflation_subspace_generation____mu.setText(_translate("Form", "0.01", None))
        self.lbl0_70.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_70.setText(_translate("Form", "Number of inverse iterations:", None))
        self.Deflation_subspace_generation____ninv.setText(_translate("Form", "9", None))
        self.lbl0_83.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_83.setText(_translate("Form", "Block solver iterations:", None))
        self.Deflation_subspace_generation____nmr.setText(_translate("Form", "4", None))
        self.lbl0_84.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_84.setText(_translate("Form", "SAP cycles:", None))
        self.Deflation_subspace_generation____ncy.setText(_translate("Form", "4", None))
        self.groupDFLprojection.setTitle(_translate("Form", "Deflation Projection", None))
        self.lbl0_85.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_85.setText(_translate("Form", "Max Krylov vectors before restart:", None))
        self.Deflation_projection____nkv.setText(_translate("Form", "24", None))
        self.lbl0_86.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_86.setText(_translate("Form", "Max total Krylov vectors:", None))
        self.Deflation_projection____nmx.setText(_translate("Form", "256", None))
        self.lbl0_87.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_87.setText(_translate("Form", "Max relative residue:", None))
        self.Deflation_projection____res.setText(_translate("Form", "1.0e-2", None))
        self.groupDFLupdate.setTitle(_translate("Form", "Deflation Update Scheme", None))
        self.lbl0_88.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_88.setText(_translate("Form", "Update interval:", None))
        self.Deflation_update_scheme____dtau.setText(_translate("Form", "0.091", None))
        self.lbl0_89.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_89.setText(_translate("Form", "Smoothing steps:", None))
        self.Deflation_update_scheme____nsm.setText(_translate("Form", "1", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabDeflation), _translate("Form", "Deflation", None))
        self.groupBox_10.setTitle(_translate("Form", "Fermion Actions", None))
        self.listActions.setSortingEnabled(False)
        self.btnAddAction.setText(_translate("Form", "Add Action", None))
        self.btnRemoveAction.setText(_translate("Form", "Remove Action", None))
        self.groupAction.setTitle(_translate("Form", "Action Parameters", None))
        self.lbl0_28.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_28.setText(_translate("Form", "Action Index:", None))
        self.lblActionIndex.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lblActionIndex.setText(_translate("Form", "0", None))
        self.lbl0_7.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_7.setText(_translate("Form", "Action:", None))
        self.Action____action.setItemText(0, _translate("Form", "ACF_TM1", None))
        self.Action____action.setItemText(1, _translate("Form", "ACF_TM2", None))
        self.Action____action.setItemText(2, _translate("Form", "ACF_TM1_EO_SDET", None))
        self.Action____action.setItemText(3, _translate("Form", "ACF_TM2_EO", None))
        self.Action____action.setItemText(4, _translate("Form", "ACF_RAT", None))
        self.Action____action.setItemText(5, _translate("Form", "ACF_RAT_SDET", None))
        self.lbl0_56.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_56.setText(_translate("Form", "Kappa:", None))
        self.lbl0_57.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_57.setText(_translate("Form", "Twisted mu_0:", None))
        self.lbl0_60.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_60.setText(_translate("Form", "Solver mu_0:", None))
        self.lbl0_58.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_58.setText(_translate("Form", "Twisted mu_1:", None))
        self.lbl0_61.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_61.setText(_translate("Form", "Solver mu_1:", None))
        self.lbl0_62.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_62.setText(_translate("Form", "Rational Approx:", None))
        self.lbl0_63.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_63.setText(_translate("Form", "Rational Poles:", None))
        self.lbl0_65.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_65.setText(_translate("Form", "from", None))
        self.lbl0_64.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_64.setText(_translate("Form", "to", None))
        self.lbl0_66.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_66.setText(_translate("Form", "Force Solver:", None))
        self.lbl0_67.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_67.setText(_translate("Form", "Extrap previous solutions: ", None))
        self.Force____ncr.setText(_translate("Form", "2", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabAction), _translate("Form", "Action", None))
        self.lbl0_35.setToolTip(_translate("Form", "can put some relevant info about beta here...", None))
        self.lbl0_35.setText(_translate("Form", "Integrator:", None))
        self.lbl0_38.setToolTip(_translate("Form", "Number of integration steps per trajectory", None))
        self.lbl0_38.setText(_translate("Form", "Forces:", None))
        self.lbl0_37.setToolTip(_translate("Form", "Number of integration steps per trajectory", None))
        self.lbl0_37.setText(_translate("Form", "Steps:", None))
        self.lbl0_36.setToolTip(_translate("Form", "can put some relevant info about gauge actions here...", None))
        self.lbl0_36.setText(_translate("Form", "Lambda:", None))
        self.label.setText(_translate("Form", "Integration Level:", None))
        self.btnAddIntLevel.setText(_translate("Form", "Add Integration Level", None))
        self.btnRemoveIntLevel.setText(_translate("Form", "Remove Integration Level", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabMDint), _translate("Form", "MD Integration", None))
        self.groupSort.setTitle(_translate("Form", "Ordering of sections", None))
        self.radioSortDefault.setText(_translate("Form", "Default", None))
        self.radioSortAlpha.setText(_translate("Form", "Alphabetical", None))
        self.radioSortOriginal.setText(_translate("Form", "Preserve Original", None))
        self.tabMain.setTabText(self.tabMain.indexOf(self.tabInputFile), _translate("Form", "Input File Preview", None))
        self.btnOpen.setText(_translate("Form", "&Open Input file... (ctrl+O)", None))
        self.btnOpen.setShortcut(_translate("Form", "Ctrl+O", None))
        self.btnSave.setText(_translate("Form", "&Save Input file... (ctrl+S)", None))
        self.btnSave.setShortcut(_translate("Form", "Ctrl+S", None))
        self.btnHelp.setText(_translate("Form", "&Help (F1)", None))
        self.btnHelp.setShortcut(_translate("Form", "F1", None))

